services:
  chick-db-service:
    build:
      context: .
      dockerfile: ./ChickDB/Dockerfile
    container_name: chick-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1!
    # Explicitly lock down port 1433 to localhost loopback rules to secure data records from external internet explotation
    ports:
      - "127.0.0.1:1433:1433"
    networks:
      - chick-network
    volumes:
      - db_data:/var/opt/mssql

  mvc-service:
    build:
      context: .               # Root context to ensure file accessibility
      dockerfile: ./ChickMVC/Dockerfile  # Path to MVC Dockerfile
    container_name: mvc-chick-service-magic
    environment:
      - SQL_CONNECTION_STRING=Server=chick-db;Database=Farm;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=false;user id=sa;password=Password1!
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    ports:
      - "80:8080"
    depends_on:
      - chick-db-service
    networks:
      - chick-network 

  api-service:
    build:
      context: .
      dockerfile: ./ChickenAPI/Dockerfile
    container_name: api-chick-service
    environment:
      - SQL_CONNECTION_STRING=Server=chick-db;Database=Farm;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=false;user id=sa;password=Password1!
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      chick-db-service:
        condition: service_healthy
    networks:
      - chick-network

networks:
  chick-network:
    driver: bridge

volumes:
  db_data: